### ISSUE TITLE
When enabling Leve Solver, the Character moves to foundation, stops in front of the leve NPC and does nothing.

### ISSUE THREAD

**Issue by Kumicoo** [ArchiDog1998/QuestSolver#5]
Title.

I also tried disabling every plugin except Quest Solver and vnavmesh - Same outcome.

Is the Leve Solver not working?

**Comment by ArchiDog1998** [comment]
Well, only Craft Leve is supported. You need to make sure that you have the things you need to take in your inventory and the right job.

I only tested it in Sharlayan with the leve `Practical Command` in the job Alchemist. It is not well-tested. This is my test record: https://www.bilibili.com/video/BV1BJ4m1T78J/

**Comment by Kumicoo** [comment]
> Well, only Craft Leve is supported. You need to make sure that you have the things you need to take in your inventory and the right job.
> 
> I only tested it in Sharlayan with the leve `Practical Command` in the job Alchemist. It is not well-tested. This is my test record: https://www.bilibili.com/video/BV1BJ4m1T78J/

Ah! The wording makes it seem that it will accept the leve, gather the ingredients, craft it and then turn it in!

Because it's called leve "solver" - i thought it will , well, solve the leves!

If it were called "Leve Turn in Assistant" or something it would be clearer.

This is not me critisizing your work! You are one of the best Plugin devs! Dont get me wrong!

Unless i misunderstood something here, it made me think it will do it all for leves 🗡️

**Comment by ArchiDog1998** [comment]
Well, I'll make it a true solver! Finish Battle, Gather leve!

It'll first get what your job is. And find the `highest level` leve quest for you. For the Craft Leve, it'll also check if the quest `Can be finished`, which means are there enough items the leve needs in your inventory! So you need to prepare the items and switch your job, and then, it'll auto-teleport you there, and auto-move and deliver the items. That's all.

**Comment by Kumicoo** [comment]
That's insane! Thank you for your hard work. You have done so much already, you are allowed to be a little lazy too. Thanks so much for the answers. I unserstand now. ♥
